# Generated by Django 4.2.2 on 2024-04-14 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Utilisateur',
        ),
    ]
