# Generated by Django 4.2.2 on 2024-04-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_reservation', '0002_rename_user_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
