# Generated by Django 4.2.2 on 2024-04-27 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_reservation', '0004_user_alter_reservation_utilisateur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('is_medecin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_reservation.utilisateur'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
