# Generated by Django 4.2.2 on 2024-07-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_reservation', '0005_utilisateur_alter_reservation_utilisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
