# Generated by Django 4.2.2 on 2024-07-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_reservation', '0006_utilisateur_adresse_utilisateur_numero_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
