# Generated by Django 4.2.2 on 2024-07-19 00:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_reservation', '0008_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
