# Generated by Django 4.2.2 on 2024-07-19 00:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_reservation', '0009_utilisateur_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Complète'), ('CANCELLED', 'Annulée'), ('UNCONFIRMED', 'Non confirmée'), ('REJECTED', 'Refusée'), ('AWAITING_PAYMENT', 'En attente de paiement'), ('AWAITING_APPROVAL', 'En attente de validation'), ('EXPIRED', 'Expirée')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
