# Generated by Django 4.2.2 on 2024-07-19 01:00

from django.db import migrations, models
import django.db.models.deletion
import site_reservation.models


class Migration(migrations.Migration):

    dependencies = [
        ('site_reservation', '0011_statut_alter_reservation_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.ForeignKey(default=site_reservation.models.get_default_statut, on_delete=django.db.models.deletion.CASCADE, to='site_reservation.statut'),
        ),
    ]
